before_script:
  - npm install

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - gitbook build
  artifacts:
    paths:
    - _book
    expire_in: 20 minutes

deploy:
  stage: deploy
  script:
    - sh .ci/deploy.sh
  only:
    - master@BJMUN/kb
  when: on_success
